name: BiocCheck

on:
  push:
    branches: [main, master, devel]
  pull_request:
    branches: [main, master, devel]

jobs:
  BiocCheck:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: Add Julia to PATH
        shell: bash
        run: echo "$(dirname $(which julia))" >> $GITHUB_PATH

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::BiocManager
            any::BiocCheck
          needs: check

      - name: Run BiocCheck
        run: |
          BiocCheck::BiocCheck(".", `no-check-R-ver` = TRUE,
                               `no-check-bioc-help` = TRUE)
        shell: Rscript {0}
